/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Shankari;
import Shankari.core.Preliminary;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import Shankari.ui.FileMenu;

import java.io.IOException;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) {

        BorderPane root = new BorderPane();
        //root.getChildren().add(btn);
        FileMenu f = new FileMenu();
        //ChartTab ct = new ChartTab();
        // menuBar.getMenus().addAll(f.getMenuBar());

        //root.getChildren().add(f.getMenuBar());


        Scene scene = new Scene(root, 300, 250);
        root.setTop(f.getMenuBar());
        //root.setCenter(ct.getTab());
        primaryStage.setTitle("Hello World!");
        primaryStage.setScene(scene);
        primaryStage.show();
        primaryStage.setMaximized(true);
    }
    public static void main(String[] args) {
        Preliminary p = new Preliminary();
        try {
            p.checkDir();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
        launch(args);
    }
}

